class Mocks:

	TOURNAMENT = [{
		"id":3771,
		"title":"Singapore 2023 Online Circuit Opener",
		"creator_id":22484,
		"creator_name":"Ghost00",
		"creator_supporter":0,
		"creator_class":"",
		"created_at":"2023.05.17. 15:57:58",
		"location":"online",
		"location_lat":"",
		"location_lng":"",
		"location_country":"",
		"location_state":"",
		"address":"",
		"store":"",
		"place_id":"ChIJzVHFNqkZ2jERboLN2YrltH8",
		"contact":"derekyang8@gmail.com",
		"approved":1,
		"registration_count":11,
		"photos":0,
		"url":"https:\/\/alwaysberunning.net\/tournaments\/3771\/singapore-2023-online-circuit-opener",
		"link_facebook":"",
		"cardpool":"Parhelion",
		"date":"2023.07.01.",
		"type":"circuit opener",
		"format":"standard",
		"mwl":"Standard Ban List 23.03",
		"concluded":1,
		"charity":0,
		"players_count":12,
		"top_count":0,
		"claim_count":5,
		"claim_conflict":0,
		"matchdata":1,
		"videos":0,
		"winner_runner_identity":"26066",
		"winner_corp_identity":"33057"
		,"rendered_in":0.8594198226928711,
		"tournament_count":2839
	},
	{
		"id":3774,
		"title":"Circuit Opener @ Deventer Library",
		"creator_id":31562,
		"creator_name":"Menghini",
		"creator_supporter":1,
		"creator_class":"supporter",
		"created_at":"2023.05.19. 12:21:06",
		"location":"Netherlands, Deventer",
		"location_lat":52.25318,
		"location_lng":6.155511,
		"location_country":"Netherlands",
		"location_state":"",
		"address":"Stromarkt 18, 7411 PK Deventer, Netherlands",
		"store":"",
		"place_id":"ChIJIwfVSWbqx0cR5zozD5y-VLc",
		"contact":"ddevries82@hotmail.com",
		"approved":1,
		"registration_count":4,
		"photos":0,
		"url":"https:\/\/alwaysberunning.net\/tournaments\/3774\/circuit-opener-deventer-library",
		"link_facebook":"",
		"cardpool":"Parhelion",
		"date":"2023.07.01.",
		"type":"circuit opener",
		"format":"standard",
		"mwl":"Standard Ban List 23.03",
		"concluded":1,
		"charity":0,
		"players_count":4,
		"top_count":0,
		"claim_count":0,
		"claim_conflict":0,
		"matchdata":1,
		"videos":0,
		"winner_runner_identity":"21063",
		"winner_corp_identity":"22026"
	},

	{"id":3789,"title":"Circuit Opener 2023 #2 in Brno","creator_id":15340,"creator_name":"Krasty","creator_supporter":1,"creator_class":"supporter","created_at":"2023.05.31. 15:11:16","location":"Czechia, Brno-st\u0159ed","location_lat":49.178417,"location_lng":16.595302,"location_country":"Czechia","location_state":"","address":"V\u00edde\u0148sk\u00e1 80, 639 00 Brno-st\u0159ed, Czechia","store":"BLACK OIL \u2013 Gaming & Social Hub","place_id":"ChIJnQu_9WmUEkcRtVnjhqAs4u0","contact":"krasty23 (at) gmail.com or just Krasty everywhere else (Discord, Slack, etc.)","approved":1,"registration_count":9,"photos":0,"url":"https:\/\/alwaysberunning.net\/tournaments\/3789\/circuit-opener-2023-2-in-brno","link_facebook":"","cardpool":"Parhelion","date":"2023.06.29.","type":"circuit opener","format":"standard","mwl":"Standard Ban List 23.03","concluded":1,"charity":0,"players_count":8,"top_count":0,"claim_count":4,"claim_conflict":0,"matchdata":1,"videos":0,"winner_runner_identity":"26066","winner_corp_identity":"21054"},{"id":3819,"title":"Fergus byebye tournament","creator_id":11224,"creator_name":"Cliquil","creator_supporter":0,"creator_class":"","created_at":"2023.06.27. 06:40:44","location":"United Kingdom, Oxford","location_lat":51.754398,"location_lng":-1.261733,"location_country":"United Kingdom","location_state":"","address":"97-98, Oxford OX1 2DF, UK","store":"Thirsty Meeples","place_id":"ChIJ25N9SaTGdkgRQZ9OKnuj-LE","contact":"guypatching@googlemail.com","approved":1,"registration_count":2,"photos":0,"url":"https:\/\/alwaysberunning.net\/tournaments\/3819\/fergus-byebye-tournament","link_facebook":"","cardpool":"Parhelion","date":"2023.06.26.","type":"GNK \/ seasonal","format":"other","mwl":"-not applicable-","concluded":1,"charity":0,"players_count":7,"top_count":"","claim_count":1,"claim_conflict":0,"matchdata":0,"videos":0,"winner_runner_identity":"30019","winner_corp_identity":"30035"}]